version: "3.7"

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
###< doctrine/doctrine-bundle ###
