sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        traces_sample_rate: 1.0
        ignore_exceptions:
          - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
          - Symfony\Component\Security\Core\Exception\AccessDeniedException
